### ISSUE TITLE
Debug Assert in Variable Order failes for rule with multiple constructors

### ISSUE THREAD

**Issue by monsterkrampe** [knowsys/nemo#438]
```
r(?x) :- b(?x), ?x = ?y, ?y = 3.
```
This rule set produces the following panic:
```
thread 'main' panicked at nemo/src/program_analysis/variable_order.rs:39:9:
assertion failed: insert_result.is_none()
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4cb3beec86178baff601529389306a4949b077ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/4cb3beec86178baff601529389306a4949b077ce/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/4cb3beec86178baff601529389306a4949b077ce/library/core/src/panicking.rs:127:5
   3: nemo::program_analysis::variable_order::VariableOrder::push_position
             at ./nemo/src/program_analysis/variable_order.rs:39:9
   4: nemo::execution::planning::arithmetic::generate_node_arithmetic
             at ./nemo/src/execution/planning/arithmetic.rs:83:9
   5: <nemo::execution::planning::plan_body_seminaive::SeminaiveStrategy as nemo::execution::planning::strategy_body::BodyStrategy>::add_plan_body
             at ./nemo/src/execution/planning/plan_body_seminaive.rs:151:45
   6: nemo::execution::rule_execution::RuleExecution::execute
             at ./nemo/src/execution/rule_execution.rs:65:25
   7: nemo::execution::execution_engine::ExecutionEngine<Strategy>::execute
             at ./nemo/src/execution/execution_engine.rs:245:38
   8: nmo::run
             at ./nemo-cli/src/main.rs:152:5
   9: nmo::main
             at ./nemo-cli/src/main.rs:241:5
  10: core::ops::function::FnOnce::call_once
             at /rustc/4cb3beec86178baff601529389306a4949b077ce/library/core/src/ops/function.rs:250:5
```

**Comment by matzemathics** [comment]
That is actually a bug in the normalization, because ?y = 3 is converted into a constructor, when it should be a constraint.
